version: '3'
services:
  app:
    build: .
    command: yarn dev 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN} 
      CLIENT_ID: ${CLIENT_ID} 
